version: "3.8"
networks:
  netor:
volumes:
  grafana_data:

services:
  grafana:
    image: grafana/grafana:7.2.0
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - netor
    
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./config/prometheus:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - netor

  netor:
    container_name: netor
    build: .
    image: josuablejeru/netor:latest
    ports:
      - 8080:8080
    networks:
      - netor
