version: "3.8"
networks:
  netor:

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - netor

  netor:
    container_name: netor
    build: .
    image: josuablejeru/netor
    ports:
      - 8080:8080
    networks:
      - netor
