version: "3.8"
networks:
  netor:

services:
  grafana:
    image: grafana/grafana:7.2.0
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/datasources:/etc/grafana/datasources
      # - ./config/grafana.ini:/etc/grafana/grafana.ini
      # - ./config/dashboards:/var/lib/grafana/dashboards
      # - ./config/plugins:/var/lib/grafana/plugins
      # - grafana_data:/var/lib/grafana
    networks:
      - netor
    
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./config/prometheus:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - netor

  netor:
    container_name: netor
    build: .
    image: josuablejeru/netor
    ports:
      - 8080:8080
    networks:
      - netor
